config/routes.rb
ZeitUndZeug::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login"}

  resources :favourites
  get "catalog/index"
  resources :projects

  root to: 'catalog#index', as: 'catalog'
  

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :user_id, :project_id, :project
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :description, :image_url, :start_date
  has_many :favourites
  before_destroy :ensure_not_referenced_by_any_favourite
  
  private
    #ensure that there are no favourites referencing this project
    def ensure_not_referenced_by_any_favourite
      if favourites.empty?
        return true
      else
        errors.add(:base, 'Favourites present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :favourites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
    @projects = Project.order(:start_date)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  # GET /favourites
  # GET /favourites.json
  
  before_filter :authenticate_user!
  
  def index
    @favourites = Favourite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favourites }
    end
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
    @favourite = Favourite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @favourite }
    end
  end

  # GET /favourites/new
  # GET /favourites/new.json
  def new
    @favourite = Favourite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favourite }
    end
  end

  # GET /favourites/1/edit
  def edit
    @favourite = Favourite.find(params[:id])
  end

  # POST /favourites
  # POST /favourites.json
  def create
    #@favourite = Favourite.new(params[:favourite]) 
    
    project = Project.find(params[:project_id])
    
    if Favourite.find_by_project_id_and_user_id(project, current_user)
      respond_to do |format|
        format.html { redirect_to catalog_url, notice: 'You already faved this project.' }
        format.json { head :no_content }
      end
    else
      @favourite = current_user.favourites.build(project: project) 
      respond_to do |format|
        if @favourite.save
          format.html { redirect_to catalog_url, notice: 'Favourite was successfully created.' }
          format.json { render json: @favourite, status: :created, location: @favourite }
        else
          format.html { render action: "new" }
          format.json { render json: @favourite.errors, status: :unprocessable_entity }
        end
      end
    end  
  end

  # PUT /favourites/1
  # PUT /favourites/1.json
  def update
    @favourite = Favourite.find(params[:id])

    respond_to do |format|
      if @favourite.update_attributes(params[:favourite])
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to favourites_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/catalog/index.html.erb
<% @projects.each do |project| %>
	<div class="project_entry">
		<%= image_tag(project.image_url) %>
		<h2><%= project.title%></h2>
		<p><%= project.description%></p>
		<p><%= project.start_date %></p>
		<p>
		   <span class="heart">&hearts;<!--&#9825;--></span> <%= project.favourites.size %>
	
			<!-- SHOULDN'T THIS BE IN THE CATALOG CONTROLLER OR SHOULD WE EVEN 
			USE ACTIVE RECORD ASSOCIATIONS AND GET RID OF THE FAVOURITES AND HAVE 
			A USER AS A FAN IN THE PROJECTS TABLE???? -->
			<% @loving_users = User.find(:all, :order => "username ASC", :joins => :favourites,
					:conditions => { :favourites => {:project_id => project.id} })%>
			<% @loving_users.each do |loving_user| %>
				<%= loving_user.username %>
			<% end %>
			<!-- -->
			
			<%= button_to 'Add to Favourites', favourites_path(project_id: project) %>	
		</p>
	</div>
<% end %>

app/views/favourites/_form.html.erb
<%= form_for(@favourite) do |f| %>
  <% if @favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% @favourite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing favourite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<h1>Listing favourites</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Fav card</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favourites.each do |favourite| %>
  <tr>
    <td><%= favourite.project_id %></td>
    <td><%= favourite.user_id %></td>
    <td><%= link_to 'Show', favourite %></td>
    <td><%= link_to 'Edit', edit_favourite_path(favourite) %></td>
    <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favourite', new_favourite_path %>

app/views/favourites/new.html.erb
<h1>New favourite</h1>

<%= render 'form' %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p>
  <b>Project:</b>
  <%= @favourite.project_id %>
</p>

<p>
  <b>User:</b>
  <%= @favourite.user_id %>
</p>


<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zeit und Zeug</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%=controller.controller_name %>'>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<header>
		<h1><%= image_tag('logo.png', :alt => 'Zeit und Zeug', :title => 'Zeit und Zeug') %></h1>
		<h2><%= @page_description || "Deine Zeit für tolle Projekte" %></h2>		
	</header>
	<div id="container">
		<div id="user_nav">
			<% if user_signed_in? %>
				Signed in as <%= current_user.username %>. <%= link_to "Sign out", destroy_user_session_path , :method => :delete %>
			
			<% else %>
				<%= link_to "Sign up", new_user_registration_path  %> or <%= link_to 'Sign in', new_user_session_path %>
			<% end %>
		</div>
		<aside>
			<nav id="main_nav">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>
		</aside>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
<% @projects.each do |project| %>
  <tr class="<%= cycle('odd','even') %>">
	<td>
	<%= link_to(project) do %>	
		<%= image_tag(project.image_url, class: 'project_thumbnail') %> 
	<% end %>
  	</td>
	
	<td class="project_info">
	<%= link_to(project) do %>
		<h2><%= project.title %></h2>
		<p><%= project.description %></p>
		<p><%= project.id %></p>
	<% end %>
    </td>
	
    <td class='project_actions'>
		<%= link_to 'Edit', edit_project_path(project) %>
    	<%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>
		<%= Favourite.where(:project_id => project.id).count %>
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @project.image_url %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>